# Generated by Django 3.1.2 on 2020-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
